### ISSUE TITLE
Changed font-family to "JetBrains Mono" to get template to work on Windows

### ISSUE THREAD

**Issue by cgranier** [CyanVoxel/Obsidian-Daily-Themes#1]
Not sure if this is a Windows issue, but when installing the JetBrains font it shows up as "JetBrains Mono" and not "JetBrainsMono Nerd Font Mono" as in the css file.

Changing this to "JetBrains Mono" correctly displays the heading and fonts on the daily templates.

**Comment by CyanVoxel** [comment]
Hmm, I'm also on Windows and how it's written in the CSS is how it shows up on my system. Maybe it's a matter of where the font from sourced from? (JetBrains, Google Fonts, GitHub, etc.)
Either way, I've added "JetBrains Mono" as an additional fallback font in commit 996413b451c7bbc62fdffac2320a108ca9537cbf, which should make it work regardless of which way the system reads the font. Let me know if this approach solves the issue for you!

**Comment by cgranier** [comment]
Thanks! I downloaded directly from the JetBrains page (via your link). Not sure why it reports it as just "JetBrains Mono".

Fix works, though. ;-)

**Comment by CyanVoxel** [comment]
Haha, weird but I'm glad it's all sorted out now!
